#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLKS")]
	public partial class QLKSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDatPhong(DatPhong instance);
    partial void UpdateDatPhong(DatPhong instance);
    partial void DeleteDatPhong(DatPhong instance);
    partial void InsertVaiTro(VaiTro instance);
    partial void UpdateVaiTro(VaiTro instance);
    partial void DeleteVaiTro(VaiTro instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertDichVuDatPhong(DichVuDatPhong instance);
    partial void UpdateDichVuDatPhong(DichVuDatPhong instance);
    partial void DeleteDichVuDatPhong(DichVuDatPhong instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertLoaiPhong(LoaiPhong instance);
    partial void UpdateLoaiPhong(LoaiPhong instance);
    partial void DeleteLoaiPhong(LoaiPhong instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertPhong(Phong instance);
    partial void UpdatePhong(Phong instance);
    partial void DeletePhong(Phong instance);
    partial void InsertThanhToan(ThanhToan instance);
    partial void UpdateThanhToan(ThanhToan instance);
    partial void DeleteThanhToan(ThanhToan instance);
    #endregion
		
		public QLKSDataContext() : 
				base(global::QuanLyKhachSan.Properties.Settings.Default.QLKSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLKSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DatPhong> DatPhongs
		{
			get
			{
				return this.GetTable<DatPhong>();
			}
		}
		
		public System.Data.Linq.Table<VaiTro> VaiTros
		{
			get
			{
				return this.GetTable<VaiTro>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<DichVuDatPhong> DichVuDatPhongs
		{
			get
			{
				return this.GetTable<DichVuDatPhong>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<LoaiPhong> LoaiPhongs
		{
			get
			{
				return this.GetTable<LoaiPhong>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<Phong> Phongs
		{
			get
			{
				return this.GetTable<Phong>();
			}
		}
		
		public System.Data.Linq.Table<ThanhToan> ThanhToans
		{
			get
			{
				return this.GetTable<ThanhToan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DatPhong")]
	public partial class DatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dat_phong_id;
		
		private int _khach_hang_id;
		
		private int _phong_id;
		
		private int _nhan_vien_id;
		
		private System.DateTime _ngay_check_in;
		
		private System.DateTime _ngay_check_out;
		
		private System.Nullable<System.DateTime> _ngay_dat;
		
		private string _trang_thai;
		
		private EntitySet<DichVuDatPhong> _DichVuDatPhongs;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<Phong> _Phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondat_phong_idChanging(int value);
    partial void Ondat_phong_idChanged();
    partial void Onkhach_hang_idChanging(int value);
    partial void Onkhach_hang_idChanged();
    partial void Onphong_idChanging(int value);
    partial void Onphong_idChanged();
    partial void Onnhan_vien_idChanging(int value);
    partial void Onnhan_vien_idChanged();
    partial void Onngay_check_inChanging(System.DateTime value);
    partial void Onngay_check_inChanged();
    partial void Onngay_check_outChanging(System.DateTime value);
    partial void Onngay_check_outChanged();
    partial void Onngay_datChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_datChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		//public DatPhong()
		//{
		//	this._DichVuDatPhongs = new EntitySet<DichVuDatPhong>(new Action<DichVuDatPhong>(this.attach_DichVuDatPhongs), new Action<DichVuDatPhong>(this.detach_DichVuDatPhongs));
		//	this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
		//	this._KhachHang = default(EntityRef<KhachHang>);
		//	this._NhanVien = default(EntityRef<NhanVien>);
		//	this._Phong = default(EntityRef<Phong>);
		//	OnCreated();
		//}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dat_phong_id
		{
			get
			{
				return this._dat_phong_id;
			}
			set
			{
				if ((this._dat_phong_id != value))
				{
					this.Ondat_phong_idChanging(value);
					this.SendPropertyChanging();
					this._dat_phong_id = value;
					this.SendPropertyChanged("dat_phong_id");
					this.Ondat_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khach_hang_id", DbType="Int NOT NULL")]
		public int khach_hang_id
		{
			get
			{
				return this._khach_hang_id;
			}
			set
			{
				if ((this._khach_hang_id != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onkhach_hang_idChanging(value);
					this.SendPropertyChanging();
					this._khach_hang_id = value;
					this.SendPropertyChanged("khach_hang_id");
					this.Onkhach_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", DbType="Int NOT NULL")]
		public int phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					if (this._Phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_vien_id", DbType="Int NOT NULL")]
		public int nhan_vien_id
		{
			get
			{
				return this._nhan_vien_id;
			}
			set
			{
				if ((this._nhan_vien_id != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnhan_vien_idChanging(value);
					this.SendPropertyChanging();
					this._nhan_vien_id = value;
					this.SendPropertyChanged("nhan_vien_id");
					this.Onnhan_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_check_in", DbType="Date NOT NULL")]
		public System.DateTime ngay_check_in
		{
			get
			{
				return this._ngay_check_in;
			}
			set
			{
				if ((this._ngay_check_in != value))
				{
					this.Onngay_check_inChanging(value);
					this.SendPropertyChanging();
					this._ngay_check_in = value;
					this.SendPropertyChanged("ngay_check_in");
					this.Onngay_check_inChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_check_out", DbType="Date NOT NULL")]
		public System.DateTime ngay_check_out
		{
			get
			{
				return this._ngay_check_out;
			}
			set
			{
				if ((this._ngay_check_out != value))
				{
					this.Onngay_check_outChanging(value);
					this.SendPropertyChanging();
					this._ngay_check_out = value;
					this.SendPropertyChanged("ngay_check_out");
					this.Onngay_check_outChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_dat", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_dat
		{
			get
			{
				return this._ngay_dat;
			}
			set
			{
				if ((this._ngay_dat != value))
				{
					this.Onngay_datChanging(value);
					this.SendPropertyChanging();
					this._ngay_dat = value;
					this.SendPropertyChanged("ngay_dat");
					this.Onngay_datChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="VarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DatPhong_DichVuDatPhong", Storage="_DichVuDatPhongs", ThisKey="dat_phong_id", OtherKey="dat_phong_id")]
		public EntitySet<DichVuDatPhong> DichVuDatPhongs
		{
			get
			{
				return this._DichVuDatPhongs;
			}
			set
			{
				this._DichVuDatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DatPhong_HoaDon", Storage="_HoaDons", ThisKey="dat_phong_id", OtherKey="dat_phong_id")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DatPhong", Storage="_KhachHang", ThisKey="khach_hang_id", OtherKey="khach_hang_id", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DatPhongs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DatPhongs.Add(this);
						this._khach_hang_id = value.khach_hang_id;
					}
					else
					{
						this._khach_hang_id = default(int);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DatPhong", Storage="_NhanVien", ThisKey="nhan_vien_id", OtherKey="nhan_vien_id", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.DatPhongs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.DatPhongs.Add(this);
						this._nhan_vien_id = value.nhan_vien_id;
					}
					else
					{
						this._nhan_vien_id = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_DatPhong", Storage="_Phong", ThisKey="phong_id", OtherKey="phong_id", IsForeignKey=true)]
		public Phong Phong
		{
			get
			{
				return this._Phong.Entity;
			}
			set
			{
				Phong previousValue = this._Phong.Entity;
				if (((previousValue != value) 
							|| (this._Phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Phong.Entity = null;
						previousValue.DatPhongs.Remove(this);
					}
					this._Phong.Entity = value;
					if ((value != null))
					{
						value.DatPhongs.Add(this);
						this._phong_id = value.phong_id;
					}
					else
					{
						this._phong_id = default(int);
					}
					this.SendPropertyChanged("Phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVuDatPhongs(DichVuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DatPhong = this;
		}
		
		private void detach_DichVuDatPhongs(DichVuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DatPhong = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.DatPhong = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.DatPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VaiTro")]
	public partial class VaiTro : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _vai_tro_id;
		
		private string _ten_vai_tro;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onvai_tro_idChanging(int value);
    partial void Onvai_tro_idChanged();
    partial void Onten_vai_troChanging(string value);
    partial void Onten_vai_troChanged();
    #endregion
		
		public VaiTro()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int vai_tro_id
		{
			get
			{
				return this._vai_tro_id;
			}
			set
			{
				if ((this._vai_tro_id != value))
				{
					this.Onvai_tro_idChanging(value);
					this.SendPropertyChanging();
					this._vai_tro_id = value;
					this.SendPropertyChanged("vai_tro_id");
					this.Onvai_tro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_vai_tro", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_vai_tro
		{
			get
			{
				return this._ten_vai_tro;
			}
			set
			{
				if ((this._ten_vai_tro != value))
				{
					this.Onten_vai_troChanging(value);
					this.SendPropertyChanging();
					this._ten_vai_tro = value;
					this.SendPropertyChanged("ten_vai_tro");
					this.Onten_vai_troChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NhanVien", Storage="_NhanViens", ThisKey="vai_tro_id", OtherKey="vai_tro_id")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.VaiTro = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dich_vu_id;
		
		private string _ten_dich_vu;
		
		private string _mo_ta;
		
		private decimal _gia;
		
		private EntitySet<DichVuDatPhong> _DichVuDatPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondich_vu_idChanging(int value);
    partial void Ondich_vu_idChanged();
    partial void Onten_dich_vuChanging(string value);
    partial void Onten_dich_vuChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void OngiaChanging(decimal value);
    partial void OngiaChanged();
    #endregion
		
		public DichVu()
		{
			this._DichVuDatPhongs = new EntitySet<DichVuDatPhong>(new Action<DichVuDatPhong>(this.attach_DichVuDatPhongs), new Action<DichVuDatPhong>(this.detach_DichVuDatPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dich_vu_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dich_vu_id
		{
			get
			{
				return this._dich_vu_id;
			}
			set
			{
				if ((this._dich_vu_id != value))
				{
					this.Ondich_vu_idChanging(value);
					this.SendPropertyChanging();
					this._dich_vu_id = value;
					this.SendPropertyChanged("dich_vu_id");
					this.Ondich_vu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_dich_vu", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_dich_vu
		{
			get
			{
				return this._ten_dich_vu;
			}
			set
			{
				if ((this._ten_dich_vu != value))
				{
					this.Onten_dich_vuChanging(value);
					this.SendPropertyChanging();
					this._ten_dich_vu = value;
					this.SendPropertyChanged("ten_dich_vu");
					this.Onten_dich_vuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_DichVuDatPhong", Storage="_DichVuDatPhongs", ThisKey="dich_vu_id", OtherKey="dich_vu_id")]
		public EntitySet<DichVuDatPhong> DichVuDatPhongs
		{
			get
			{
				return this._DichVuDatPhongs;
			}
			set
			{
				this._DichVuDatPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DichVuDatPhongs(DichVuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_DichVuDatPhongs(DichVuDatPhong entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVuDatPhong")]
	public partial class DichVuDatPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _dich_vu_dat_phong_id;
		
		private int _dat_phong_id;
		
		private int _dich_vu_id;
		
		private System.Nullable<int> _so_luong;
		
		private System.DateTime _ngay_su_dung;
		
		private EntityRef<DatPhong> _DatPhong;
		
		private EntityRef<DichVu> _DichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondich_vu_dat_phong_idChanging(int value);
    partial void Ondich_vu_dat_phong_idChanged();
    partial void Ondat_phong_idChanging(int value);
    partial void Ondat_phong_idChanged();
    partial void Ondich_vu_idChanging(int value);
    partial void Ondich_vu_idChanged();
    partial void Onso_luongChanging(System.Nullable<int> value);
    partial void Onso_luongChanged();
    partial void Onngay_su_dungChanging(System.DateTime value);
    partial void Onngay_su_dungChanged();
    #endregion
		
		public DichVuDatPhong()
		{
			this._DatPhong = default(EntityRef<DatPhong>);
			this._DichVu = default(EntityRef<DichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dich_vu_dat_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int dich_vu_dat_phong_id
		{
			get
			{
				return this._dich_vu_dat_phong_id;
			}
			set
			{
				if ((this._dich_vu_dat_phong_id != value))
				{
					this.Ondich_vu_dat_phong_idChanging(value);
					this.SendPropertyChanging();
					this._dich_vu_dat_phong_id = value;
					this.SendPropertyChanged("dich_vu_dat_phong_id");
					this.Ondich_vu_dat_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_phong_id", DbType="Int NOT NULL")]
		public int dat_phong_id
		{
			get
			{
				return this._dat_phong_id;
			}
			set
			{
				if ((this._dat_phong_id != value))
				{
					if (this._DatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondat_phong_idChanging(value);
					this.SendPropertyChanging();
					this._dat_phong_id = value;
					this.SendPropertyChanged("dat_phong_id");
					this.Ondat_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dich_vu_id", DbType="Int NOT NULL")]
		public int dich_vu_id
		{
			get
			{
				return this._dich_vu_id;
			}
			set
			{
				if ((this._dich_vu_id != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondich_vu_idChanging(value);
					this.SendPropertyChanging();
					this._dich_vu_id = value;
					this.SendPropertyChanged("dich_vu_id");
					this.Ondich_vu_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_luong", DbType="Int")]
		public System.Nullable<int> so_luong
		{
			get
			{
				return this._so_luong;
			}
			set
			{
				if ((this._so_luong != value))
				{
					this.Onso_luongChanging(value);
					this.SendPropertyChanging();
					this._so_luong = value;
					this.SendPropertyChanged("so_luong");
					this.Onso_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_su_dung", DbType="Date NOT NULL")]
		public System.DateTime ngay_su_dung
		{
			get
			{
				return this._ngay_su_dung;
			}
			set
			{
				if ((this._ngay_su_dung != value))
				{
					this.Onngay_su_dungChanging(value);
					this.SendPropertyChanging();
					this._ngay_su_dung = value;
					this.SendPropertyChanged("ngay_su_dung");
					this.Onngay_su_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DatPhong_DichVuDatPhong", Storage="_DatPhong", ThisKey="dat_phong_id", OtherKey="dat_phong_id", IsForeignKey=true)]
		public DatPhong DatPhong
		{
			get
			{
				return this._DatPhong.Entity;
			}
			set
			{
				DatPhong previousValue = this._DatPhong.Entity;
				if (((previousValue != value) 
							|| (this._DatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DatPhong.Entity = null;
						previousValue.DichVuDatPhongs.Remove(this);
					}
					this._DatPhong.Entity = value;
					if ((value != null))
					{
						value.DichVuDatPhongs.Add(this);
						this._dat_phong_id = value.dat_phong_id;
					}
					else
					{
						this._dat_phong_id = default(int);
					}
					this.SendPropertyChanged("DatPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_DichVuDatPhong", Storage="_DichVu", ThisKey="dich_vu_id", OtherKey="dich_vu_id", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.DichVuDatPhongs.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.DichVuDatPhongs.Add(this);
						this._dich_vu_id = value.dich_vu_id;
					}
					else
					{
						this._dich_vu_id = default(int);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _hoa_don_id;
		
		private int _dat_phong_id;
		
		private int _nhan_vien_id;
		
		private System.Nullable<System.DateTime> _ngay_tao;
		
		private decimal _tong_tien;
		
		private EntitySet<ThanhToan> _ThanhToans;
		
		private EntityRef<DatPhong> _DatPhong;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhoa_don_idChanging(int value);
    partial void Onhoa_don_idChanged();
    partial void Ondat_phong_idChanging(int value);
    partial void Ondat_phong_idChanged();
    partial void Onnhan_vien_idChanging(int value);
    partial void Onnhan_vien_idChanged();
    partial void Onngay_taoChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_taoChanged();
    partial void Ontong_tienChanging(decimal value);
    partial void Ontong_tienChanged();
    #endregion
		
		public HoaDon()
		{
			this._ThanhToans = new EntitySet<ThanhToan>(new Action<ThanhToan>(this.attach_ThanhToans), new Action<ThanhToan>(this.detach_ThanhToans));
			this._DatPhong = default(EntityRef<DatPhong>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dat_phong_id", DbType="Int NOT NULL")]
		public int dat_phong_id
		{
			get
			{
				return this._dat_phong_id;
			}
			set
			{
				if ((this._dat_phong_id != value))
				{
					if (this._DatPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondat_phong_idChanging(value);
					this.SendPropertyChanging();
					this._dat_phong_id = value;
					this.SendPropertyChanged("dat_phong_id");
					this.Ondat_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_vien_id", DbType="Int NOT NULL")]
		public int nhan_vien_id
		{
			get
			{
				return this._nhan_vien_id;
			}
			set
			{
				if ((this._nhan_vien_id != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onnhan_vien_idChanging(value);
					this.SendPropertyChanging();
					this._nhan_vien_id = value;
					this.SendPropertyChanged("nhan_vien_id");
					this.Onnhan_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_tao", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_tao
		{
			get
			{
				return this._ngay_tao;
			}
			set
			{
				if ((this._ngay_tao != value))
				{
					this.Onngay_taoChanging(value);
					this.SendPropertyChanging();
					this._ngay_tao = value;
					this.SendPropertyChanged("ngay_tao");
					this.Onngay_taoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tong_tien", DbType="Decimal(10,2) NOT NULL")]
		public decimal tong_tien
		{
			get
			{
				return this._tong_tien;
			}
			set
			{
				if ((this._tong_tien != value))
				{
					this.Ontong_tienChanging(value);
					this.SendPropertyChanging();
					this._tong_tien = value;
					this.SendPropertyChanged("tong_tien");
					this.Ontong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ThanhToan", Storage="_ThanhToans", ThisKey="hoa_don_id", OtherKey="hoa_don_id")]
		public EntitySet<ThanhToan> ThanhToans
		{
			get
			{
				return this._ThanhToans;
			}
			set
			{
				this._ThanhToans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DatPhong_HoaDon", Storage="_DatPhong", ThisKey="dat_phong_id", OtherKey="dat_phong_id", IsForeignKey=true)]
		public DatPhong DatPhong
		{
			get
			{
				return this._DatPhong.Entity;
			}
			set
			{
				DatPhong previousValue = this._DatPhong.Entity;
				if (((previousValue != value) 
							|| (this._DatPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DatPhong.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._DatPhong.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._dat_phong_id = value.dat_phong_id;
					}
					else
					{
						this._dat_phong_id = default(int);
					}
					this.SendPropertyChanged("DatPhong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_NhanVien", ThisKey="nhan_vien_id", OtherKey="nhan_vien_id", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._nhan_vien_id = value.nhan_vien_id;
					}
					else
					{
						this._nhan_vien_id = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_ThanhToans(ThanhToan entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _khach_hang_id;
		
		private string _ho_ten;
		
		private string _dia_chi;
		
		private string _so_dien_thoai;
		
		private string _email;
		
		private string _cccd;
		
		private EntitySet<DatPhong> _DatPhongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onkhach_hang_idChanging(int value);
    partial void Onkhach_hang_idChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Ondia_chiChanging(string value);
    partial void Ondia_chiChanged();
    partial void Onso_dien_thoaiChanging(string value);
    partial void Onso_dien_thoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    #endregion
		
		public KhachHang()
		{
			this._DatPhongs = new EntitySet<DatPhong>(new Action<DatPhong>(this.attach_DatPhongs), new Action<DatPhong>(this.detach_DatPhongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_khach_hang_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int khach_hang_id
		{
			get
			{
				return this._khach_hang_id;
			}
			set
			{
				if ((this._khach_hang_id != value))
				{
					this.Onkhach_hang_idChanging(value);
					this.SendPropertyChanging();
					this._khach_hang_id = value;
					this.SendPropertyChanged("khach_hang_id");
					this.Onkhach_hang_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dia_chi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string dia_chi
		{
			get
			{
				return this._dia_chi;
			}
			set
			{
				if ((this._dia_chi != value))
				{
					this.Ondia_chiChanging(value);
					this.SendPropertyChanging();
					this._dia_chi = value;
					this.SendPropertyChanged("dia_chi");
					this.Ondia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_dien_thoai", DbType="VarChar(15)")]
		public string so_dien_thoai
		{
			get
			{
				return this._so_dien_thoai;
			}
			set
			{
				if ((this._so_dien_thoai != value))
				{
					this.Onso_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._so_dien_thoai = value;
					this.SendPropertyChanged("so_dien_thoai");
					this.Onso_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DatPhong", Storage="_DatPhongs", ThisKey="khach_hang_id", OtherKey="khach_hang_id")]
		public EntitySet<DatPhong> DatPhongs
		{
			get
			{
				return this._DatPhongs;
			}
			set
			{
				this._DatPhongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiPhong")]
	public partial class LoaiPhong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _loai_phong_id;
		
		private string _ten_loai;
		
		private string _mo_ta;
		
		private decimal _gia_theo_dem;
		
		private EntitySet<Phong> _Phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onloai_phong_idChanging(int value);
    partial void Onloai_phong_idChanged();
    partial void Onten_loaiChanging(string value);
    partial void Onten_loaiChanged();
    partial void Onmo_taChanging(string value);
    partial void Onmo_taChanged();
    partial void Ongia_theo_demChanging(decimal value);
    partial void Ongia_theo_demChanged();
    #endregion
		
		public LoaiPhong()
		{
			this._Phongs = new EntitySet<Phong>(new Action<Phong>(this.attach_Phongs), new Action<Phong>(this.detach_Phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int loai_phong_id
		{
			get
			{
				return this._loai_phong_id;
			}
			set
			{
				if ((this._loai_phong_id != value))
				{
					this.Onloai_phong_idChanging(value);
					this.SendPropertyChanging();
					this._loai_phong_id = value;
					this.SendPropertyChanged("loai_phong_id");
					this.Onloai_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_loai", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ten_loai
		{
			get
			{
				return this._ten_loai;
			}
			set
			{
				if ((this._ten_loai != value))
				{
					this.Onten_loaiChanging(value);
					this.SendPropertyChanging();
					this._ten_loai = value;
					this.SendPropertyChanged("ten_loai");
					this.Onten_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_ta", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string mo_ta
		{
			get
			{
				return this._mo_ta;
			}
			set
			{
				if ((this._mo_ta != value))
				{
					this.Onmo_taChanging(value);
					this.SendPropertyChanging();
					this._mo_ta = value;
					this.SendPropertyChanged("mo_ta");
					this.Onmo_taChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia_theo_dem", DbType="Decimal(10,2) NOT NULL")]
		public decimal gia_theo_dem
		{
			get
			{
				return this._gia_theo_dem;
			}
			set
			{
				if ((this._gia_theo_dem != value))
				{
					this.Ongia_theo_demChanging(value);
					this.SendPropertyChanging();
					this._gia_theo_dem = value;
					this.SendPropertyChanged("gia_theo_dem");
					this.Ongia_theo_demChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_Phongs", ThisKey="loai_phong_id", OtherKey="loai_phong_id")]
		public EntitySet<Phong> Phongs
		{
			get
			{
				return this._Phongs;
			}
			set
			{
				this._Phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = this;
		}
		
		private void detach_Phongs(Phong entity)
		{
			this.SendPropertyChanging();
			entity.LoaiPhong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _nhan_vien_id;
		
		private string _ho_ten;
		
		private int _vai_tro_id;
		
		private string _ca_lam_viec;
		
		private System.Nullable<decimal> _luong;
		
		private EntitySet<DatPhong> _DatPhongs;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<VaiTro> _VaiTro;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnhan_vien_idChanging(int value);
    partial void Onnhan_vien_idChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onvai_tro_idChanging(int value);
    partial void Onvai_tro_idChanged();
    partial void Onca_lam_viecChanging(string value);
    partial void Onca_lam_viecChanged();
    partial void OnluongChanging(System.Nullable<decimal> value);
    partial void OnluongChanged();
    #endregion
		
		public NhanVien()
		{
			this._DatPhongs = new EntitySet<DatPhong>(new Action<DatPhong>(this.attach_DatPhongs), new Action<DatPhong>(this.detach_DatPhongs));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._VaiTro = default(EntityRef<VaiTro>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhan_vien_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int nhan_vien_id
		{
			get
			{
				return this._nhan_vien_id;
			}
			set
			{
				if ((this._nhan_vien_id != value))
				{
					this.Onnhan_vien_idChanging(value);
					this.SendPropertyChanging();
					this._nhan_vien_id = value;
					this.SendPropertyChanged("nhan_vien_id");
					this.Onnhan_vien_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vai_tro_id", DbType="Int NOT NULL")]
		public int vai_tro_id
		{
			get
			{
				return this._vai_tro_id;
			}
			set
			{
				if ((this._vai_tro_id != value))
				{
					if (this._VaiTro.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onvai_tro_idChanging(value);
					this.SendPropertyChanging();
					this._vai_tro_id = value;
					this.SendPropertyChanged("vai_tro_id");
					this.Onvai_tro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_lam_viec", DbType="VarChar(50)")]
		public string ca_lam_viec
		{
			get
			{
				return this._ca_lam_viec;
			}
			set
			{
				if ((this._ca_lam_viec != value))
				{
					this.Onca_lam_viecChanging(value);
					this.SendPropertyChanging();
					this._ca_lam_viec = value;
					this.SendPropertyChanged("ca_lam_viec");
					this.Onca_lam_viecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this.OnluongChanging(value);
					this.SendPropertyChanging();
					this._luong = value;
					this.SendPropertyChanged("luong");
					this.OnluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_DatPhong", Storage="_DatPhongs", ThisKey="nhan_vien_id", OtherKey="nhan_vien_id")]
		public EntitySet<DatPhong> DatPhongs
		{
			get
			{
				return this._DatPhongs;
			}
			set
			{
				this._DatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_HoaDon", Storage="_HoaDons", ThisKey="nhan_vien_id", OtherKey="nhan_vien_id")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="VaiTro_NhanVien", Storage="_VaiTro", ThisKey="vai_tro_id", OtherKey="vai_tro_id", IsForeignKey=true)]
		public VaiTro VaiTro
		{
			get
			{
				return this._VaiTro.Entity;
			}
			set
			{
				VaiTro previousValue = this._VaiTro.Entity;
				if (((previousValue != value) 
							|| (this._VaiTro.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._VaiTro.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._VaiTro.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._vai_tro_id = value.vai_tro_id;
					}
					else
					{
						this._vai_tro_id = default(int);
					}
					this.SendPropertyChanged("VaiTro");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Phong")]
	public partial class Phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _phong_id;
		
		private string _so_phong;
		
		private int _loai_phong_id;
		
		private string _trang_thai;
		
		private EntitySet<DatPhong> _DatPhongs;
		
		private EntityRef<LoaiPhong> _LoaiPhong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onphong_idChanging(int value);
    partial void Onphong_idChanged();
    partial void Onso_phongChanging(string value);
    partial void Onso_phongChanged();
    partial void Onloai_phong_idChanging(int value);
    partial void Onloai_phong_idChanged();
    partial void Ontrang_thaiChanging(string value);
    partial void Ontrang_thaiChanged();
    #endregion
		
		public Phong()
		{
			this._DatPhongs = new EntitySet<DatPhong>(new Action<DatPhong>(this.attach_DatPhongs), new Action<DatPhong>(this.detach_DatPhongs));
			this._LoaiPhong = default(EntityRef<LoaiPhong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phong_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int phong_id
		{
			get
			{
				return this._phong_id;
			}
			set
			{
				if ((this._phong_id != value))
				{
					this.Onphong_idChanging(value);
					this.SendPropertyChanging();
					this._phong_id = value;
					this.SendPropertyChanged("phong_id");
					this.Onphong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_phong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string so_phong
		{
			get
			{
				return this._so_phong;
			}
			set
			{
				if ((this._so_phong != value))
				{
					this.Onso_phongChanging(value);
					this.SendPropertyChanging();
					this._so_phong = value;
					this.SendPropertyChanged("so_phong");
					this.Onso_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai_phong_id", DbType="Int NOT NULL")]
		public int loai_phong_id
		{
			get
			{
				return this._loai_phong_id;
			}
			set
			{
				if ((this._loai_phong_id != value))
				{
					if (this._LoaiPhong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onloai_phong_idChanging(value);
					this.SendPropertyChanging();
					this._loai_phong_id = value;
					this.SendPropertyChanged("loai_phong_id");
					this.Onloai_phong_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trang_thai", DbType="VarChar(20)")]
		public string trang_thai
		{
			get
			{
				return this._trang_thai;
			}
			set
			{
				if ((this._trang_thai != value))
				{
					this.Ontrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._trang_thai = value;
					this.SendPropertyChanged("trang_thai");
					this.Ontrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Phong_DatPhong", Storage="_DatPhongs", ThisKey="phong_id", OtherKey="phong_id")]
		public EntitySet<DatPhong> DatPhongs
		{
			get
			{
				return this._DatPhongs;
			}
			set
			{
				this._DatPhongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiPhong_Phong", Storage="_LoaiPhong", ThisKey="loai_phong_id", OtherKey="loai_phong_id", IsForeignKey=true)]
		public LoaiPhong LoaiPhong
		{
			get
			{
				return this._LoaiPhong.Entity;
			}
			set
			{
				LoaiPhong previousValue = this._LoaiPhong.Entity;
				if (((previousValue != value) 
							|| (this._LoaiPhong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiPhong.Entity = null;
						previousValue.Phongs.Remove(this);
					}
					this._LoaiPhong.Entity = value;
					if ((value != null))
					{
						value.Phongs.Add(this);
						this._loai_phong_id = value.loai_phong_id;
					}
					else
					{
						this._loai_phong_id = default(int);
					}
					this.SendPropertyChanged("LoaiPhong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = this;
		}
		
		private void detach_DatPhongs(DatPhong entity)
		{
			this.SendPropertyChanging();
			entity.Phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThanhToan")]
	public partial class ThanhToan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _thanh_toan_id;
		
		private int _hoa_don_id;
		
		private decimal _so_tien;
		
		private string _phuong_thuc;
		
		private System.Nullable<System.DateTime> _ngay_thanh_toan;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onthanh_toan_idChanging(int value);
    partial void Onthanh_toan_idChanged();
    partial void Onhoa_don_idChanging(int value);
    partial void Onhoa_don_idChanged();
    partial void Onso_tienChanging(decimal value);
    partial void Onso_tienChanged();
    partial void Onphuong_thucChanging(string value);
    partial void Onphuong_thucChanged();
    partial void Onngay_thanh_toanChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_thanh_toanChanged();
    #endregion
		
		public ThanhToan()
		{
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanh_toan_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int thanh_toan_id
		{
			get
			{
				return this._thanh_toan_id;
			}
			set
			{
				if ((this._thanh_toan_id != value))
				{
					this.Onthanh_toan_idChanging(value);
					this.SendPropertyChanging();
					this._thanh_toan_id = value;
					this.SendPropertyChanged("thanh_toan_id");
					this.Onthanh_toan_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoa_don_id", DbType="Int NOT NULL")]
		public int hoa_don_id
		{
			get
			{
				return this._hoa_don_id;
			}
			set
			{
				if ((this._hoa_don_id != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhoa_don_idChanging(value);
					this.SendPropertyChanging();
					this._hoa_don_id = value;
					this.SendPropertyChanged("hoa_don_id");
					this.Onhoa_don_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_so_tien", DbType="Decimal(10,2) NOT NULL")]
		public decimal so_tien
		{
			get
			{
				return this._so_tien;
			}
			set
			{
				if ((this._so_tien != value))
				{
					this.Onso_tienChanging(value);
					this.SendPropertyChanging();
					this._so_tien = value;
					this.SendPropertyChanged("so_tien");
					this.Onso_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phuong_thuc", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string phuong_thuc
		{
			get
			{
				return this._phuong_thuc;
			}
			set
			{
				if ((this._phuong_thuc != value))
				{
					this.Onphuong_thucChanging(value);
					this.SendPropertyChanging();
					this._phuong_thuc = value;
					this.SendPropertyChanged("phuong_thuc");
					this.Onphuong_thucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_thanh_toan", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngay_thanh_toan
		{
			get
			{
				return this._ngay_thanh_toan;
			}
			set
			{
				if ((this._ngay_thanh_toan != value))
				{
					this.Onngay_thanh_toanChanging(value);
					this.SendPropertyChanging();
					this._ngay_thanh_toan = value;
					this.SendPropertyChanged("ngay_thanh_toan");
					this.Onngay_thanh_toanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ThanhToan", Storage="_HoaDon", ThisKey="hoa_don_id", OtherKey="hoa_don_id", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.ThanhToans.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.ThanhToans.Add(this);
						this._hoa_don_id = value.hoa_don_id;
					}
					else
					{
						this._hoa_don_id = default(int);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
