<?xml version="1.0" encoding="utf-8"?><Database Name="QLKS" Class="QLKSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-R1ZAX\MSSQLSERVER01;Initial Catalog=QLKS;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="QuanLyKhachSan.Properties.Settings" SettingsPropertyName="QLKSConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DatPhong" Member="DatPhongs">
    <Type Name="DatPhong">
      <Column Name="dat_phong_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="khach_hang_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="khuyen_mai_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nhan_vien_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_check_in" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngay_check_out" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngay_dat" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="DatPhong_DichVuDatPhong" Member="DichVuDatPhongs" ThisKey="dat_phong_id" OtherKey="dat_phong_id" Type="DichVuDatPhong" />
      <Association Name="DatPhong_HoaDon" Member="HoaDons" ThisKey="dat_phong_id" OtherKey="dat_phong_id" Type="HoaDon" />
      <Association Name="KhachHang_DatPhong" Member="KhachHang" ThisKey="khach_hang_id" OtherKey="khach_hang_id" Type="KhachHang" IsForeignKey="true" />
      <Association Name="KhuyenMai_DatPhong" Member="KhuyenMai" ThisKey="khuyen_mai_id" OtherKey="khuyen_mai_id" Type="KhuyenMai" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="NhanVien_DatPhong" Member="NhanVien" ThisKey="nhan_vien_id" OtherKey="nhan_vien_id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="Phong_DatPhong" Member="Phong" ThisKey="phong_id" OtherKey="phong_id" Type="Phong" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VaiTro" Member="VaiTros">
    <Type Name="VaiTro">
      <Column Name="vai_tro_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_vai_tro" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="VaiTro_NhanVien" Member="NhanViens" ThisKey="vai_tro_id" OtherKey="vai_tro_id" Type="NhanVien" />
    </Type>
  </Table>
  <Table Name="dbo.DichVu" Member="DichVus">
    <Type Name="DichVu">
      <Column Name="dich_vu_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_dich_vu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="mo_ta" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="DichVu_DichVuDatPhong" Member="DichVuDatPhongs" ThisKey="dich_vu_id" OtherKey="dich_vu_id" Type="DichVuDatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.DichVuDatPhong" Member="DichVuDatPhongs">
    <Type Name="DichVuDatPhong">
      <Column Name="dich_vu_dat_phong_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dat_phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="dich_vu_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ngay_su_dung" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="DatPhong_DichVuDatPhong" Member="DatPhong" ThisKey="dat_phong_id" OtherKey="dat_phong_id" Type="DatPhong" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="DichVu_DichVuDatPhong" Member="DichVu" ThisKey="dich_vu_id" OtherKey="dich_vu_id" Type="DichVu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="hoa_don_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dat_phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nhan_vien_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ten_nhan_vien" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tong_tien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_ThanhToan" Member="ThanhToans" ThisKey="hoa_don_id" OtherKey="hoa_don_id" Type="ThanhToan" />
      <Association Name="DatPhong_HoaDon" Member="DatPhong" ThisKey="dat_phong_id" OtherKey="dat_phong_id" Type="DatPhong" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="NhanVien_HoaDon" Member="NhanVien" ThisKey="nhan_vien_id" OtherKey="nhan_vien_id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="khach_hang_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ho_ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="dia_chi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="so_dien_thoai" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="cccd" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="KhachHang_DatPhong" Member="DatPhongs" ThisKey="khach_hang_id" OtherKey="khach_hang_id" Type="DatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.KhuyenMai" Member="KhuyenMais">
    <Type Name="KhuyenMai">
      <Column Name="khuyen_mai_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_khuyen_mai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phan_tram" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_bat_dau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngay_ket_thuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="KhuyenMai_DatPhong" Member="DatPhongs" ThisKey="khuyen_mai_id" OtherKey="khuyen_mai_id" Type="DatPhong" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiPhong" Member="LoaiPhongs">
    <Type Name="LoaiPhong">
      <Column Name="loai_phong_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ten_loai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="mo_ta" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gia_theo_dem" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="LoaiPhong_Phong" Member="Phongs" ThisKey="loai_phong_id" OtherKey="loai_phong_id" Type="Phong" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="nhan_vien_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ho_ten" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="sdt" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="vai_tro_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ca_lam_viec" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="luong" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="tai_khoan" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="mat_khau" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="NhanVien_DatPhong" Member="DatPhongs" ThisKey="nhan_vien_id" OtherKey="nhan_vien_id" Type="DatPhong" />
      <Association Name="NhanVien_HoaDon" Member="HoaDons" ThisKey="nhan_vien_id" OtherKey="nhan_vien_id" Type="HoaDon" />
      <Association Name="VaiTro_NhanVien" Member="VaiTro" ThisKey="vai_tro_id" OtherKey="vai_tro_id" Type="VaiTro" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Phong" Member="Phongs">
    <Type Name="Phong">
      <Column Name="phong_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="so_phong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="loai_phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="trang_thai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="Phong_DatPhong" Member="DatPhongs" ThisKey="phong_id" OtherKey="phong_id" Type="DatPhong" />
      <Association Name="LoaiPhong_Phong" Member="LoaiPhong" ThisKey="loai_phong_id" OtherKey="loai_phong_id" Type="LoaiPhong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhToan" Member="ThanhToans">
    <Type Name="ThanhToan">
      <Column Name="thanh_toan_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hoa_don_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="so_tien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="phuong_thuc" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ngay_thanh_toan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="HoaDon_ThanhToan" Member="HoaDon" ThisKey="hoa_don_id" OtherKey="hoa_don_id" Type="HoaDon" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_ThongTinHoaDon" Method="sp_ThongTinHoaDon">
    <Parameter Name="hoa_don_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ThongTinHoaDonResult">
      <Column Name="hoa_don_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ngay_tao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="tong_tien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="khach_hang" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="phong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="ngay_check_in" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ngay_check_out" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ten_dich_vu" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="so_luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="gia" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ThongKeDatPhong" Method="sp_ThongKeDatPhong">
    <ElementType Name="sp_ThongKeDatPhongResult">
      <Column Name="loai_phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="loai_phong_dat_nhieu_nhat" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="so_lan_dat_loai_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="phong_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="phong_dat_nhieu_nhat" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="so_lan_dat_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tong_dat_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tong_so_phong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ty_le_dat_phong" Type="System.Decimal" DbType="Decimal(26,12)" CanBeNull="true" />
      <Column Name="so_dat_ngay" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ty_le_dat_ngay" Type="System.Decimal" DbType="Decimal(26,12)" CanBeNull="true" />
      <Column Name="so_ngay_trong_data" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trung_binh_dat_tren_ngay" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="so_thang_trong_data" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="trung_binh_dat_tren_thang" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>